name: DEPLOY
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: rsync deployments
        uses: burnett01/rsync-deployments@v9
        with:
          switches: -avzr --delete
          path: src/
          remote_path: ${{ secrets.REMOTE_PATH }} # ex: /var/www/html/
          remote_host: ${{ secrets.HOST }} # ex: example.com
          remote_user: ${{ secrets.USERNAME }} # ex: ubuntu
          remote_key: ${{ secrets.SSH_KEY }}
